-- MySQL Script generated by MySQL Workbench
-- Fri Feb 26 18:52:51 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema bookstore
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema bookstore
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `bookstore` DEFAULT CHARACTER SET utf8 ;
USE `bookstore` ;

-- -----------------------------------------------------
-- Table `bookstore`.`BookAuthor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bookstore`.`BookAuthor` (
  `idAuthor` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idAuthor`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bookstore`.`BookInventory`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bookstore`.`BookInventory` (
  `idBooks` INT NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(45) NOT NULL,
  `price` FLOAT NOT NULL,
  `image` VARCHAR(45) NOT NULL,
  `quantity` VARCHAR(45) NOT NULL,
  `Author_idAuthor` INT NOT NULL,
  PRIMARY KEY (`idBooks`, `Author_idAuthor`),
  CONSTRAINT `fk_Books_Author`
    FOREIGN KEY (`Author_idAuthor`)
    REFERENCES `bookstore`.`BookAuthor` (`idAuthor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
